package com.priyanshparekh.solarsystem.model

data class Body(
    val alternativeName: String,
    val aphelion: Long,
    val argPeriapsis: Double,
    val aroundPlanet: AroundPlanet,
    val avgTemp: Int,
    val axialTilt: Double,
    val bodyType: String,
    val density: Double,
    val dimension: String,
    val discoveredBy: String,
    val discoveryDate: String,
    val eccentricity: Double,
    val englishName: String,
    val equaRadius: Double,
    val escape: Double,
    val flattening: Double,
    val gravity: Double,
    val id: String,
    val inclination: Double,
    val isPlanet: Boolean,
    val longAscNode: Double,
    val mainAnomaly: Double,
    val mass: Mass,
    val meanRadius: Double,
    val moons: List<Moon>,
    val name: String,
    val perihelion: Long,
    val polarRadius: Double,
    val rel: String,
    val semimajorAxis: Long,
    val sideralOrbit: Double,
    val sideralRotation: Double,
    val vol: Vol
)